SCML: Raise ValueError if n_features larger than n_triplets
scikit-learn-contrib/metric-learn pull request #350
Opened 2022-04-07 11:55 UTC by nikosmichas

Related discussion https://github.com/scikit-learn-contrib/metric-learn/issues/348
cc @grudloff

2022-04-07 16:32 UTC, grudloff commented on metric_learn/scml.py
> +        "Number of features (%s) is greater than the nuber of triplets(%s).\n"
small typo

2022-04-07 22:00 UTC, nikosmichas commented on metric_learn/scml.py
> +        "Number of features (%s) is greater than the nuber of triplets(%s).\n"
fixed

2022-04-07 22:00 UTC, nikosmichas commented on metric_learn/scml.py
> +
thanks, updated

2022-06-20 08:21 UTC, bellet requested changes
Thanks for the work @nikosmichas !
This looks good to me, except that I realize that the docstring entry for the `‘triplet_diffs’` option says:

```
The basis set is constructed from the differences between points of n_basis positive or negative pairs taken from the triplets constrains.
```

Shoudn't it be something like:

```
Each basis is constructed from the differences between points of n_features positive or negative pairs taken randomly from the triplets constraints.
```

2022-06-20 11:36 UTC, nikosmichas commented
> Thanks for the work @nikosmichas ! This looks good to me, except that I realize that the docstring entry for the `‘triplet_diffs’` option says:
> 
> ```
> The basis set is constructed from the differences between points of n_basis positive or negative pairs taken from the triplets constrains.
> ```
> 
> Shoudn't it be something like:
> 
> ```
> Each basis is constructed from the differences between points of n_features positive or negative pairs taken randomly from the triplets constraints.
> ```

@bellet not sure about the exact wording. I can make the docstring change if you think that it's better. Do you thing that the change is related to this PR ?

2022-06-20 23:53 UTC, merged

2022-06-20 23:54 UTC, perimosocordiae commented
Merging now, we can fix the docstring separately.

2022-06-21 07:56 UTC, bellet commented
Thanks @nikosmichas !